/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { ErrorT, ErrorT$inboundSchema } from "./error.js";
import {
  PageNotFoundError,
  PageNotFoundError$inboundSchema,
} from "./pagenotfounderror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

/**
 * Invalid query parameters or page number
 */
export type GetV1AuthorsBadRequest = ErrorT | PageNotFoundError;

/** @internal */
export const GetV1AuthorsBadRequest$inboundSchema: z.ZodMiniType<
  GetV1AuthorsBadRequest,
  unknown
> = smartUnion([ErrorT$inboundSchema, PageNotFoundError$inboundSchema]);

export function getV1AuthorsBadRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AuthorsBadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AuthorsBadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AuthorsBadRequest' from JSON`,
  );
}
