/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";
import { MarbleError } from "./marbleerror.js";

export type PageNotFoundErrorData = {
  error: models.ErrorT;
  details: models.Details;
};

export class PageNotFoundError extends MarbleError {
  error: models.ErrorT;
  details: models.Details;

  /** The original data that was passed to this error instance. */
  data$: PageNotFoundErrorData;

  constructor(
    err: PageNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    this.details = err.details;

    this.name = "PageNotFoundError";
  }
}

/** @internal */
export const PageNotFoundError$inboundSchema: z.ZodMiniType<
  PageNotFoundError,
  unknown
> = z.pipe(
  z.object({
    error: models.ErrorT$inboundSchema,
    details: z.lazy(() => models.Details$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new PageNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
