/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { MarbleError } from "./marbleerror.js";

export type ServerErrorData = {
  error: string;
  message?: string | undefined;
};

export class ServerError extends MarbleError {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: ServerErrorData;

  constructor(
    err: ServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "ServerError";
  }
}

/** @internal */
export const ServerError$inboundSchema: z.ZodMiniType<ServerError, unknown> = z
  .pipe(
    z.object({
      error: types.string(),
      message: types.optional(types.string()),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new ServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
