/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authorsCreate } from "../funcs/authorsCreate.js";
import { authorsDelete } from "../funcs/authorsDelete.js";
import { authorsGet } from "../funcs/authorsGet.js";
import { authorsList } from "../funcs/authorsList.js";
import { authorsUpdate } from "../funcs/authorsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Authors extends ClientSDK {
  /**
   * List authors
   *
   * @remarks
   * Get a paginated list of authors who have published posts
   */
  async list(
    request?: operations.GetV1AuthorsRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.GetV1AuthorsResponse, { page: number }>> {
    return unwrapResultIterator(authorsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create author
   *
   * @remarks
   * Create a new author. Requires a private API key. Hobby plan is limited to 1 author.
   */
  async create(
    request: models.CreateAuthorBody,
    options?: RequestOptions,
  ): Promise<models.CreateAuthorResponse> {
    return unwrapAsync(authorsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get author
   *
   * @remarks
   * Get a single author by ID or slug
   */
  async get(
    request: operations.GetV1AuthorsIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.AuthorResponse> {
    return unwrapAsync(authorsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update author
   *
   * @remarks
   * Update an existing author by ID or slug. Requires a private API key.
   */
  async update(
    request: operations.PatchV1AuthorsIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.CreateAuthorResponse> {
    return unwrapAsync(authorsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete author
   *
   * @remarks
   * Delete an author by ID or slug. Requires a private API key.
   */
  async delete(
    request: operations.DeleteV1AuthorsIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.DeleteResponse> {
    return unwrapAsync(authorsDelete(
      this,
      request,
      options,
    ));
  }
}
