/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authorsGet } from "../funcs/authorsGet.js";
import { authorsList } from "../funcs/authorsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Authors extends ClientSDK {
  /**
   * List authors
   *
   * @remarks
   * Get a paginated list of authors who have published posts
   */
  async list(
    request?: operations.GetV1AuthorsRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.GetV1AuthorsResponse, { page: number }>> {
    return unwrapResultIterator(authorsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get author
   *
   * @remarks
   * Get a single author by ID or slug
   */
  async get(
    request: operations.GetV1AuthorsIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.AuthorResponse> {
    return unwrapAsync(authorsGet(
      this,
      request,
      options,
    ));
  }
}
