/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { categoriesGet } from "../funcs/categoriesGet.js";
import { categoriesList } from "../funcs/categoriesList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Categories extends ClientSDK {
  /**
   * List categories
   *
   * @remarks
   * Get a paginated list of categories
   */
  async list(
    request?: operations.GetV1CategoriesRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.GetV1CategoriesResponse, { page: number }>
  > {
    return unwrapResultIterator(categoriesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a category
   *
   * @remarks
   * Get a single category by ID or slug
   */
  async get(
    request: operations.GetV1CategoriesIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.SingleCategoryResponse> {
    return unwrapAsync(categoriesGet(
      this,
      request,
      options,
    ));
  }
}
