/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { categoriesDeleteV1CategoriesIdentifier } from "../funcs/categoriesDeleteV1CategoriesIdentifier.js";
import { categoriesGet } from "../funcs/categoriesGet.js";
import { categoriesList } from "../funcs/categoriesList.js";
import { categoriesPatchV1CategoriesIdentifier } from "../funcs/categoriesPatchV1CategoriesIdentifier.js";
import { categoriesPostV1Categories } from "../funcs/categoriesPostV1Categories.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Categories extends ClientSDK {
  /**
   * List categories
   *
   * @remarks
   * Get a paginated list of categories
   */
  async list(
    request?: operations.GetV1CategoriesRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.GetV1CategoriesResponse, { page: number }>
  > {
    return unwrapResultIterator(categoriesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create category
   *
   * @remarks
   * Create a new category. Requires a private API key.
   */
  async postV1Categories(
    request: models.CreateCategoryBody,
    options?: RequestOptions,
  ): Promise<models.CreateCategoryResponse> {
    return unwrapAsync(categoriesPostV1Categories(
      this,
      request,
      options,
    ));
  }

  /**
   * Get category
   *
   * @remarks
   * Get a single category by ID or slug
   */
  async get(
    request: operations.GetV1CategoriesIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.CategoryResponse> {
    return unwrapAsync(categoriesGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update category
   *
   * @remarks
   * Update an existing category by ID or slug. Requires a private API key.
   */
  async patchV1CategoriesIdentifier(
    request: operations.PatchV1CategoriesIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.CreateCategoryResponse> {
    return unwrapAsync(categoriesPatchV1CategoriesIdentifier(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete category
   *
   * @remarks
   * Delete a category by ID or slug. Requires a private API key. Cannot delete a category that has posts assigned to it.
   */
  async deleteV1CategoriesIdentifier(
    request: operations.DeleteV1CategoriesIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.DeleteResponse> {
    return unwrapAsync(categoriesDeleteV1CategoriesIdentifier(
      this,
      request,
      options,
    ));
  }
}
