/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { fieldsDeleteV1FieldsIdentifier } from "../funcs/fieldsDeleteV1FieldsIdentifier.js";
import { fieldsGetV1Fields } from "../funcs/fieldsGetV1Fields.js";
import { fieldsGetV1FieldsIdentifier } from "../funcs/fieldsGetV1FieldsIdentifier.js";
import { fieldsPatchV1FieldsIdentifier } from "../funcs/fieldsPatchV1FieldsIdentifier.js";
import { fieldsPostV1Fields } from "../funcs/fieldsPostV1Fields.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Fields extends ClientSDK {
  /**
   * List fields
   *
   * @remarks
   * Get all custom field definitions for the workspace.
   */
  async getV1Fields(
    options?: RequestOptions,
  ): Promise<models.FieldsListResponse> {
    return unwrapAsync(fieldsGetV1Fields(
      this,
      options,
    ));
  }

  /**
   * Create field
   *
   * @remarks
   * Create a custom field definition. Requires a private API key.
   */
  async postV1Fields(
    request: models.CreateFieldBody,
    options?: RequestOptions,
  ): Promise<models.FieldResponse> {
    return unwrapAsync(fieldsPostV1Fields(
      this,
      request,
      options,
    ));
  }

  /**
   * Get field
   *
   * @remarks
   * Get a single custom field definition by ID or key.
   */
  async getV1FieldsIdentifier(
    request: operations.GetV1FieldsIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.FieldResponse> {
    return unwrapAsync(fieldsGetV1FieldsIdentifier(
      this,
      request,
      options,
    ));
  }

  /**
   * Update field
   *
   * @remarks
   * Update a custom field definition by ID or key. Type and options cannot be changed after values have been saved.
   */
  async patchV1FieldsIdentifier(
    request: operations.PatchV1FieldsIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.FieldResponse> {
    return unwrapAsync(fieldsPatchV1FieldsIdentifier(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete field
   *
   * @remarks
   * Delete a custom field definition by ID or key. Requires a private API key.
   */
  async deleteV1FieldsIdentifier(
    request: operations.DeleteV1FieldsIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.DeleteResponse> {
    return unwrapAsync(fieldsDeleteV1FieldsIdentifier(
      this,
      request,
      options,
    ));
  }
}
