/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { fieldsCreate } from "../funcs/fieldsCreate.js";
import { fieldsDelete } from "../funcs/fieldsDelete.js";
import { fieldsGet } from "../funcs/fieldsGet.js";
import { fieldsList } from "../funcs/fieldsList.js";
import { fieldsUpdate } from "../funcs/fieldsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Fields extends ClientSDK {
  /**
   * List fields
   *
   * @remarks
   * Get all custom field definitions for the workspace.
   */
  async list(
    options?: RequestOptions,
  ): Promise<models.FieldsListResponse> {
    return unwrapAsync(fieldsList(
      this,
      options,
    ));
  }

  /**
   * Create field
   *
   * @remarks
   * Create a custom field definition. Requires a private API key.
   */
  async create(
    request: models.CreateFieldBody,
    options?: RequestOptions,
  ): Promise<models.FieldResponse> {
    return unwrapAsync(fieldsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get field
   *
   * @remarks
   * Get a single custom field definition by ID or key.
   */
  async get(
    request: operations.GetV1FieldsIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.FieldResponse> {
    return unwrapAsync(fieldsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update field
   *
   * @remarks
   * Update a custom field definition by ID or key. Type and options cannot be changed after values have been saved.
   */
  async update(
    request: operations.PatchV1FieldsIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.FieldResponse> {
    return unwrapAsync(fieldsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete field
   *
   * @remarks
   * Delete a custom field definition by ID or key. Requires a private API key.
   */
  async delete(
    request: operations.DeleteV1FieldsIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.DeleteResponse> {
    return unwrapAsync(fieldsDelete(
      this,
      request,
      options,
    ));
  }
}
