/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mediaDeleteV1MediaId } from "../funcs/mediaDeleteV1MediaId.js";
import { mediaGetV1Media } from "../funcs/mediaGetV1Media.js";
import { mediaGetV1MediaId } from "../funcs/mediaGetV1MediaId.js";
import { mediaPatchV1MediaId } from "../funcs/mediaPatchV1MediaId.js";
import { mediaPostV1MediaUpload } from "../funcs/mediaPostV1MediaUpload.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Media extends ClientSDK {
  /**
   * List media assets
   *
   * @remarks
   * Retrieve media assets for the authenticated workspace.
   */
  async getV1Media(
    request?: operations.GetV1MediaRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.MediaListResponse> {
    return unwrapAsync(mediaGetV1Media(
      this,
      request,
      options,
    ));
  }

  /**
   * Get media asset
   *
   * @remarks
   * Retrieve a single media asset by ID.
   */
  async getV1MediaId(
    request: operations.GetV1MediaIdRequest,
    options?: RequestOptions,
  ): Promise<models.MediaResponse> {
    return unwrapAsync(mediaGetV1MediaId(
      this,
      request,
      options,
    ));
  }

  /**
   * Update media asset
   *
   * @remarks
   * Update media asset metadata. Requires a private API key.
   */
  async patchV1MediaId(
    request: operations.PatchV1MediaIdRequest,
    options?: RequestOptions,
  ): Promise<models.MediaResponse> {
    return unwrapAsync(mediaPatchV1MediaId(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete media asset
   *
   * @remarks
   * Delete a media asset and its R2 object. Requires a private API key.
   */
  async deleteV1MediaId(
    request: operations.DeleteV1MediaIdRequest,
    options?: RequestOptions,
  ): Promise<models.DeleteResponse> {
    return unwrapAsync(mediaDeleteV1MediaId(
      this,
      request,
      options,
    ));
  }

  /**
   * Upload media asset
   *
   * @remarks
   * Upload a media file and create a media asset. Requires a private API key. Maximum file size is 5 MiB.
   */
  async postV1MediaUpload(
    request: models.UploadMediaBody,
    options?: RequestOptions,
  ): Promise<models.MediaResponse> {
    return unwrapAsync(mediaPostV1MediaUpload(
      this,
      request,
      options,
    ));
  }
}
