/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mediaDelete } from "../funcs/mediaDelete.js";
import { mediaGet } from "../funcs/mediaGet.js";
import { mediaList } from "../funcs/mediaList.js";
import { mediaUpdate } from "../funcs/mediaUpdate.js";
import { mediaUpload } from "../funcs/mediaUpload.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Media extends ClientSDK {
  /**
   * List media assets
   *
   * @remarks
   * Retrieve media assets for the authenticated workspace.
   */
  async list(
    request?: operations.GetV1MediaRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.GetV1MediaResponse, { page: number }>> {
    return unwrapResultIterator(mediaList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get media asset
   *
   * @remarks
   * Retrieve a single media asset by ID.
   */
  async get(
    request: operations.GetV1MediaIdRequest,
    options?: RequestOptions,
  ): Promise<models.MediaResponse> {
    return unwrapAsync(mediaGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update media asset
   *
   * @remarks
   * Update media asset metadata. Requires a private API key.
   */
  async update(
    request: operations.PatchV1MediaIdRequest,
    options?: RequestOptions,
  ): Promise<models.MediaResponse> {
    return unwrapAsync(mediaUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete media asset
   *
   * @remarks
   * Delete a media asset and its R2 object. Requires a private API key.
   */
  async delete(
    request: operations.DeleteV1MediaIdRequest,
    options?: RequestOptions,
  ): Promise<models.DeleteResponse> {
    return unwrapAsync(mediaDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Upload media asset
   *
   * @remarks
   * Upload a media file and create a media asset. Requires a private API key. Maximum file size is 5 MiB.
   */
  async upload(
    request: models.UploadMediaBody,
    options?: RequestOptions,
  ): Promise<models.MediaResponse> {
    return unwrapAsync(mediaUpload(
      this,
      request,
      options,
    ));
  }
}
