/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { postsCreate } from "../funcs/postsCreate.js";
import { postsDelete } from "../funcs/postsDelete.js";
import { postsGet } from "../funcs/postsGet.js";
import { postsList } from "../funcs/postsList.js";
import { postsUpdate } from "../funcs/postsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Posts extends ClientSDK {
  /**
   * List posts
   *
   * @remarks
   * Get a paginated list of published posts with optional filtering
   */
  async list(
    request?: operations.GetV1PostsRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.GetV1PostsResponse, { page: number }>> {
    return unwrapResultIterator(postsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create post
   *
   * @remarks
   * Create a new post. Requires a private API key. Category is required. If authors are not provided, the first workspace author is used.
   */
  async create(
    request: models.CreatePostBody,
    options?: RequestOptions,
  ): Promise<models.CreatePostResponse> {
    return unwrapAsync(postsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get post
   *
   * @remarks
   * Get a single post by ID or slug, with optional status filtering
   */
  async get(
    request: operations.GetV1PostsIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.PostResponse> {
    return unwrapAsync(postsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update post
   *
   * @remarks
   * Update an existing post by ID or slug. All fields are optional — only provided fields are updated. Requires a private API key.
   */
  async update(
    request: operations.PatchV1PostsIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.UpdatePostResponse> {
    return unwrapAsync(postsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete post
   *
   * @remarks
   * Delete a post by ID or slug. Requires a private API key.
   */
  async delete(
    request: operations.DeleteV1PostsIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.DeleteResponse> {
    return unwrapAsync(postsDelete(
      this,
      request,
      options,
    ));
  }
}
