/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { postsGet } from "../funcs/postsGet.js";
import { postsList } from "../funcs/postsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Posts extends ClientSDK {
  /**
   * List posts
   *
   * @remarks
   * Get a paginated list of published posts with optional filtering
   */
  async list(
    request?: operations.GetV1PostsRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.GetV1PostsResponse, { page: number }>> {
    return unwrapResultIterator(postsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get post
   *
   * @remarks
   * Get a single post by ID or slug, with optional status filtering
   */
  async get(
    request: operations.GetV1PostsIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.PostResponse> {
    return unwrapAsync(postsGet(
      this,
      request,
      options,
    ));
  }
}
