/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Authors } from "./authors.js";
import { Categories } from "./categories.js";
import { Posts } from "./posts.js";
import { Tags } from "./tags.js";

export class Marble extends ClientSDK {
  private _posts?: Posts;
  get posts(): Posts {
    return (this._posts ??= new Posts(this._options));
  }

  private _categories?: Categories;
  get categories(): Categories {
    return (this._categories ??= new Categories(this._options));
  }

  private _tags?: Tags;
  get tags(): Tags {
    return (this._tags ??= new Tags(this._options));
  }

  private _authors?: Authors;
  get authors(): Authors {
    return (this._authors ??= new Authors(this._options));
  }
}
