/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tagsDeleteV1TagsIdentifier } from "../funcs/tagsDeleteV1TagsIdentifier.js";
import { tagsGet } from "../funcs/tagsGet.js";
import { tagsList } from "../funcs/tagsList.js";
import { tagsPatchV1TagsIdentifier } from "../funcs/tagsPatchV1TagsIdentifier.js";
import { tagsPostV1Tags } from "../funcs/tagsPostV1Tags.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Tags extends ClientSDK {
  /**
   * List tags
   *
   * @remarks
   * Get a paginated list of tags
   */
  async list(
    request?: operations.GetV1TagsRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.GetV1TagsResponse, { page: number }>> {
    return unwrapResultIterator(tagsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create tag
   *
   * @remarks
   * Create a new tag. Requires a private API key.
   */
  async postV1Tags(
    request: models.CreateTagBody,
    options?: RequestOptions,
  ): Promise<models.CreateTagResponse> {
    return unwrapAsync(tagsPostV1Tags(
      this,
      request,
      options,
    ));
  }

  /**
   * Get tag
   *
   * @remarks
   * Get a single tag by ID or slug
   */
  async get(
    request: operations.GetV1TagsIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.TagResponse> {
    return unwrapAsync(tagsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update tag
   *
   * @remarks
   * Update an existing tag by ID or slug. Requires a private API key.
   */
  async patchV1TagsIdentifier(
    request: operations.PatchV1TagsIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.CreateTagResponse> {
    return unwrapAsync(tagsPatchV1TagsIdentifier(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete tag
   *
   * @remarks
   * Delete a tag by ID or slug. Requires a private API key.
   */
  async deleteV1TagsIdentifier(
    request: operations.DeleteV1TagsIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.DeleteResponse> {
    return unwrapAsync(tagsDeleteV1TagsIdentifier(
      this,
      request,
      options,
    ));
  }
}
