/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tagsGet } from "../funcs/tagsGet.js";
import { tagsList } from "../funcs/tagsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Tags extends ClientSDK {
  /**
   * List tags
   *
   * @remarks
   * Get a paginated list of tags
   */
  async list(
    request?: operations.GetV1TagsRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.GetV1TagsResponse, { page: number }>> {
    return unwrapResultIterator(tagsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get tag
   *
   * @remarks
   * Get a single tag by ID or slug
   */
  async get(
    request: operations.GetV1TagsIdentifierRequest,
    options?: RequestOptions,
  ): Promise<models.TagResponse> {
    return unwrapAsync(tagsGet(
      this,
      request,
      options,
    ));
  }
}
