/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @usemarble/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx postsList.example.ts
 */

import { Marble } from "@usemarble/sdk";

const marble = new Marble({
  apiKey: process.env["MARBLE_API_KEY"] ?? "",
});

async function main() {
  const result = await marble.posts.list({
    limit: 10,
    page: 1,
    categories: "tech,news",
    excludeCategories: "changelog",
    tags: "javascript,react",
    excludeTags: "outdated",
    query: "nextjs",
    format: "html",
    featured: "true",
  });

  for await (const page of result) {
    console.log(page);
  }
}

main().catch(console.error);
