/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteV1AuthorsIdentifierRequest = {
  /**
   * Author ID or slug
   */
  identifier: string;
};

/** @internal */
export type DeleteV1AuthorsIdentifierRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const DeleteV1AuthorsIdentifierRequest$outboundSchema: z.ZodMiniType<
  DeleteV1AuthorsIdentifierRequest$Outbound,
  DeleteV1AuthorsIdentifierRequest
> = z.object({
  identifier: z.string(),
});

export function deleteV1AuthorsIdentifierRequestToJSON(
  deleteV1AuthorsIdentifierRequest: DeleteV1AuthorsIdentifierRequest,
): string {
  return JSON.stringify(
    DeleteV1AuthorsIdentifierRequest$outboundSchema.parse(
      deleteV1AuthorsIdentifierRequest,
    ),
  );
}
