/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteV1PostsIdentifierRequest = {
  /**
   * Post ID or slug
   */
  identifier: string;
};

/** @internal */
export type DeleteV1PostsIdentifierRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const DeleteV1PostsIdentifierRequest$outboundSchema: z.ZodMiniType<
  DeleteV1PostsIdentifierRequest$Outbound,
  DeleteV1PostsIdentifierRequest
> = z.object({
  identifier: z.string(),
});

export function deleteV1PostsIdentifierRequestToJSON(
  deleteV1PostsIdentifierRequest: DeleteV1PostsIdentifierRequest,
): string {
  return JSON.stringify(
    DeleteV1PostsIdentifierRequest$outboundSchema.parse(
      deleteV1PostsIdentifierRequest,
    ),
  );
}
