/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteV1CategoriesIdentifierRequest = {
  /**
   * Category ID or slug
   */
  identifier: string;
};

/** @internal */
export type DeleteV1CategoriesIdentifierRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const DeleteV1CategoriesIdentifierRequest$outboundSchema: z.ZodMiniType<
  DeleteV1CategoriesIdentifierRequest$Outbound,
  DeleteV1CategoriesIdentifierRequest
> = z.object({
  identifier: z.string(),
});

export function deleteV1CategoriesIdentifierRequestToJSON(
  deleteV1CategoriesIdentifierRequest: DeleteV1CategoriesIdentifierRequest,
): string {
  return JSON.stringify(
    DeleteV1CategoriesIdentifierRequest$outboundSchema.parse(
      deleteV1CategoriesIdentifierRequest,
    ),
  );
}
