/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteV1FieldsIdentifierRequest = {
  /**
   * Field ID or key
   */
  identifier: string;
};

/** @internal */
export type DeleteV1FieldsIdentifierRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const DeleteV1FieldsIdentifierRequest$outboundSchema: z.ZodMiniType<
  DeleteV1FieldsIdentifierRequest$Outbound,
  DeleteV1FieldsIdentifierRequest
> = z.object({
  identifier: z.string(),
});

export function deleteV1FieldsIdentifierRequestToJSON(
  deleteV1FieldsIdentifierRequest: DeleteV1FieldsIdentifierRequest,
): string {
  return JSON.stringify(
    DeleteV1FieldsIdentifierRequest$outboundSchema.parse(
      deleteV1FieldsIdentifierRequest,
    ),
  );
}
