/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteV1TagsIdentifierRequest = {
  /**
   * Tag ID or slug
   */
  identifier: string;
};

/** @internal */
export type DeleteV1TagsIdentifierRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const DeleteV1TagsIdentifierRequest$outboundSchema: z.ZodMiniType<
  DeleteV1TagsIdentifierRequest$Outbound,
  DeleteV1TagsIdentifierRequest
> = z.object({
  identifier: z.string(),
});

export function deleteV1TagsIdentifierRequestToJSON(
  deleteV1TagsIdentifierRequest: DeleteV1TagsIdentifierRequest,
): string {
  return JSON.stringify(
    DeleteV1TagsIdentifierRequest$outboundSchema.parse(
      deleteV1TagsIdentifierRequest,
    ),
  );
}
