/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteV1MediaIdRequest = {
  /**
   * Media asset ID
   */
  id: string;
};

/** @internal */
export type DeleteV1MediaIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteV1MediaIdRequest$outboundSchema: z.ZodMiniType<
  DeleteV1MediaIdRequest$Outbound,
  DeleteV1MediaIdRequest
> = z.object({
  id: z.string(),
});

export function deleteV1MediaIdRequestToJSON(
  deleteV1MediaIdRequest: DeleteV1MediaIdRequest,
): string {
  return JSON.stringify(
    DeleteV1MediaIdRequest$outboundSchema.parse(deleteV1MediaIdRequest),
  );
}
