/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetV1MediaIdRequest = {
  /**
   * Media asset ID
   */
  id: string;
};

/** @internal */
export type GetV1MediaIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1MediaIdRequest$outboundSchema: z.ZodMiniType<
  GetV1MediaIdRequest$Outbound,
  GetV1MediaIdRequest
> = z.object({
  id: z.string(),
});

export function getV1MediaIdRequestToJSON(
  getV1MediaIdRequest: GetV1MediaIdRequest,
): string {
  return JSON.stringify(
    GetV1MediaIdRequest$outboundSchema.parse(getV1MediaIdRequest),
  );
}
