/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetV1CategoriesRequest = {
  /**
   * Number of items per page (1-100)
   */
  limit?: number | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
};

export type GetV1CategoriesResponse = {
  result: models.CategoriesListResponse;
};

/** @internal */
export type GetV1CategoriesRequest$Outbound = {
  limit: number;
  page: number;
};

/** @internal */
export const GetV1CategoriesRequest$outboundSchema: z.ZodMiniType<
  GetV1CategoriesRequest$Outbound,
  GetV1CategoriesRequest
> = z.object({
  limit: z._default(z.int(), 10),
  page: z._default(z.int(), 1),
});

export function getV1CategoriesRequestToJSON(
  getV1CategoriesRequest: GetV1CategoriesRequest,
): string {
  return JSON.stringify(
    GetV1CategoriesRequest$outboundSchema.parse(getV1CategoriesRequest),
  );
}

/** @internal */
export const GetV1CategoriesResponse$inboundSchema: z.ZodMiniType<
  GetV1CategoriesResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.CategoriesListResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function getV1CategoriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CategoriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CategoriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CategoriesResponse' from JSON`,
  );
}
