/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetV1TagsRequest = {
  /**
   * Number of items per page (1-100)
   */
  limit?: number | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
};

export type GetV1TagsResponse = {
  result: models.TagsListResponse;
};

/** @internal */
export type GetV1TagsRequest$Outbound = {
  limit: number;
  page: number;
};

/** @internal */
export const GetV1TagsRequest$outboundSchema: z.ZodMiniType<
  GetV1TagsRequest$Outbound,
  GetV1TagsRequest
> = z.object({
  limit: z._default(z.int(), 10),
  page: z._default(z.int(), 1),
});

export function getV1TagsRequestToJSON(
  getV1TagsRequest: GetV1TagsRequest,
): string {
  return JSON.stringify(
    GetV1TagsRequest$outboundSchema.parse(getV1TagsRequest),
  );
}

/** @internal */
export const GetV1TagsResponse$inboundSchema: z.ZodMiniType<
  GetV1TagsResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.TagsListResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function getV1TagsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1TagsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1TagsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1TagsResponse' from JSON`,
  );
}
