/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetV1FieldsIdentifierRequest = {
  /**
   * Field ID or key
   */
  identifier: string;
};

/** @internal */
export type GetV1FieldsIdentifierRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const GetV1FieldsIdentifierRequest$outboundSchema: z.ZodMiniType<
  GetV1FieldsIdentifierRequest$Outbound,
  GetV1FieldsIdentifierRequest
> = z.object({
  identifier: z.string(),
});

export function getV1FieldsIdentifierRequestToJSON(
  getV1FieldsIdentifierRequest: GetV1FieldsIdentifierRequest,
): string {
  return JSON.stringify(
    GetV1FieldsIdentifierRequest$outboundSchema.parse(
      getV1FieldsIdentifierRequest,
    ),
  );
}
