/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetV1TagsIdentifierRequest = {
  /**
   * Tag ID or slug
   */
  identifier: string;
};

/** @internal */
export type GetV1TagsIdentifierRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const GetV1TagsIdentifierRequest$outboundSchema: z.ZodMiniType<
  GetV1TagsIdentifierRequest$Outbound,
  GetV1TagsIdentifierRequest
> = z.object({
  identifier: z.string(),
});

export function getV1TagsIdentifierRequestToJSON(
  getV1TagsIdentifierRequest: GetV1TagsIdentifierRequest,
): string {
  return JSON.stringify(
    GetV1TagsIdentifierRequest$outboundSchema.parse(getV1TagsIdentifierRequest),
  );
}
