/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetV1AuthorsRequest = {
  /**
   * Number of items per page (1-100)
   */
  limit?: number | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
};

export type GetV1AuthorsResponse = {
  result: models.AuthorsListResponse;
};

/** @internal */
export type GetV1AuthorsRequest$Outbound = {
  limit: number;
  page: number;
};

/** @internal */
export const GetV1AuthorsRequest$outboundSchema: z.ZodMiniType<
  GetV1AuthorsRequest$Outbound,
  GetV1AuthorsRequest
> = z.object({
  limit: z._default(z.int(), 10),
  page: z._default(z.int(), 1),
});

export function getV1AuthorsRequestToJSON(
  getV1AuthorsRequest: GetV1AuthorsRequest,
): string {
  return JSON.stringify(
    GetV1AuthorsRequest$outboundSchema.parse(getV1AuthorsRequest),
  );
}

/** @internal */
export const GetV1AuthorsResponse$inboundSchema: z.ZodMiniType<
  GetV1AuthorsResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.AuthorsListResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function getV1AuthorsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AuthorsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AuthorsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AuthorsResponse' from JSON`,
  );
}
