/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type GetV1PostsIdentifierRequest = {
  /**
   * Post ID or slug
   */
  identifier: string;
  /**
   * Content format (html or markdown)
   */
  format?: models.ContentFormat | undefined;
};

/** @internal */
export type GetV1PostsIdentifierRequest$Outbound = {
  identifier: string;
  format?: string | undefined;
};

/** @internal */
export const GetV1PostsIdentifierRequest$outboundSchema: z.ZodMiniType<
  GetV1PostsIdentifierRequest$Outbound,
  GetV1PostsIdentifierRequest
> = z.object({
  identifier: z.string(),
  format: z.optional(models.ContentFormat$outboundSchema),
});

export function getV1PostsIdentifierRequestToJSON(
  getV1PostsIdentifierRequest: GetV1PostsIdentifierRequest,
): string {
  return JSON.stringify(
    GetV1PostsIdentifierRequest$outboundSchema.parse(
      getV1PostsIdentifierRequest,
    ),
  );
}
