/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";
import * as models from "../index.js";

/**
 * Filter by post status. Use 'published' for live posts, 'draft' for unpublished posts, or 'all' for both.
 */
export const GetV1PostsIdentifierStatus = {
  Published: "published",
  Draft: "draft",
  All: "all",
} as const;
/**
 * Filter by post status. Use 'published' for live posts, 'draft' for unpublished posts, or 'all' for both.
 */
export type GetV1PostsIdentifierStatus = ClosedEnum<
  typeof GetV1PostsIdentifierStatus
>;

export type GetV1PostsIdentifierRequest = {
  /**
   * Post ID or slug
   */
  identifier: string;
  /**
   * Content format (html or markdown)
   */
  format?: models.ContentFormat | undefined;
  /**
   * Filter by post status. Use 'published' for live posts, 'draft' for unpublished posts, or 'all' for both.
   */
  status?: GetV1PostsIdentifierStatus | undefined;
};

/** @internal */
export const GetV1PostsIdentifierStatus$outboundSchema: z.ZodMiniEnum<
  typeof GetV1PostsIdentifierStatus
> = z.enum(GetV1PostsIdentifierStatus);

/** @internal */
export type GetV1PostsIdentifierRequest$Outbound = {
  identifier: string;
  format?: string | undefined;
  status: string;
};

/** @internal */
export const GetV1PostsIdentifierRequest$outboundSchema: z.ZodMiniType<
  GetV1PostsIdentifierRequest$Outbound,
  GetV1PostsIdentifierRequest
> = z.object({
  identifier: z.string(),
  format: z.optional(models.ContentFormat$outboundSchema),
  status: z._default(GetV1PostsIdentifierStatus$outboundSchema, "published"),
});

export function getV1PostsIdentifierRequestToJSON(
  getV1PostsIdentifierRequest: GetV1PostsIdentifierRequest,
): string {
  return JSON.stringify(
    GetV1PostsIdentifierRequest$outboundSchema.parse(
      getV1PostsIdentifierRequest,
    ),
  );
}
