/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetV1CategoriesIdentifierRequest = {
  /**
   * Category ID or slug
   */
  identifier: string;
};

/** @internal */
export type GetV1CategoriesIdentifierRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const GetV1CategoriesIdentifierRequest$outboundSchema: z.ZodMiniType<
  GetV1CategoriesIdentifierRequest$Outbound,
  GetV1CategoriesIdentifierRequest
> = z.object({
  identifier: z.string(),
});

export function getV1CategoriesIdentifierRequestToJSON(
  getV1CategoriesIdentifierRequest: GetV1CategoriesIdentifierRequest,
): string {
  return JSON.stringify(
    GetV1CategoriesIdentifierRequest$outboundSchema.parse(
      getV1CategoriesIdentifierRequest,
    ),
  );
}
