/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetV1AuthorsIdentifierRequest = {
  /**
   * Author ID or slug
   */
  identifier: string;
};

/** @internal */
export type GetV1AuthorsIdentifierRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const GetV1AuthorsIdentifierRequest$outboundSchema: z.ZodMiniType<
  GetV1AuthorsIdentifierRequest$Outbound,
  GetV1AuthorsIdentifierRequest
> = z.object({
  identifier: z.string(),
});

export function getV1AuthorsIdentifierRequestToJSON(
  getV1AuthorsIdentifierRequest: GetV1AuthorsIdentifierRequest,
): string {
  return JSON.stringify(
    GetV1AuthorsIdentifierRequest$outboundSchema.parse(
      getV1AuthorsIdentifierRequest,
    ),
  );
}
