/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * Sort order by publishedAt
 */
export const Order = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * Sort order by publishedAt
 */
export type Order = ClosedEnum<typeof Order>;

export type GetV1PostsRequest = {
  /**
   * Number of posts per page (1-100)
   */
  limit?: number | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Sort order by publishedAt
   */
  order?: Order | undefined;
  /**
   * Comma-separated category slugs to include
   */
  categories?: string | undefined;
  /**
   * Comma-separated category slugs to exclude
   */
  excludeCategories?: string | undefined;
  /**
   * Comma-separated tag slugs to include
   */
  tags?: string | undefined;
  /**
   * Comma-separated tag slugs to exclude
   */
  excludeTags?: string | undefined;
  /**
   * Search query for title and content
   */
  query?: string | undefined;
  /**
   * Content format (html or markdown)
   */
  format?: models.ContentFormat | undefined;
};

export type GetV1PostsResponse = {
  result: models.PostsListResponse;
};

/** @internal */
export const Order$outboundSchema: z.ZodMiniEnum<typeof Order> = z.enum(Order);

/** @internal */
export type GetV1PostsRequest$Outbound = {
  limit?: number | undefined;
  page?: number | undefined;
  order: string;
  categories?: string | undefined;
  excludeCategories?: string | undefined;
  tags?: string | undefined;
  excludeTags?: string | undefined;
  query?: string | undefined;
  format?: string | undefined;
};

/** @internal */
export const GetV1PostsRequest$outboundSchema: z.ZodMiniType<
  GetV1PostsRequest$Outbound,
  GetV1PostsRequest
> = z.object({
  limit: z.optional(z.int()),
  page: z.optional(z.int()),
  order: z._default(Order$outboundSchema, "desc"),
  categories: z.optional(z.string()),
  excludeCategories: z.optional(z.string()),
  tags: z.optional(z.string()),
  excludeTags: z.optional(z.string()),
  query: z.optional(z.string()),
  format: z.optional(models.ContentFormat$outboundSchema),
});

export function getV1PostsRequestToJSON(
  getV1PostsRequest: GetV1PostsRequest,
): string {
  return JSON.stringify(
    GetV1PostsRequest$outboundSchema.parse(getV1PostsRequest),
  );
}

/** @internal */
export const GetV1PostsResponse$inboundSchema: z.ZodMiniType<
  GetV1PostsResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.PostsListResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function getV1PostsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1PostsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1PostsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1PostsResponse' from JSON`,
  );
}
