/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * Filter by inferred media type
 */
export const Type = {
  Image: "image",
  Video: "video",
  Audio: "audio",
  Document: "document",
} as const;
/**
 * Filter by inferred media type
 */
export type Type = ClosedEnum<typeof Type>;

/**
 * Sort order by creation date
 */
export const GetV1MediaOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * Sort order by creation date
 */
export type GetV1MediaOrder = ClosedEnum<typeof GetV1MediaOrder>;

export type GetV1MediaRequest = {
  /**
   * Number of items per page (1-100)
   */
  limit?: number | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Search media by name, alt text, URL, or MIME type
   */
  query?: string | undefined;
  /**
   * Filter by inferred media type
   */
  type?: Type | undefined;
  /**
   * Sort order by creation date
   */
  order?: GetV1MediaOrder | undefined;
};

export type GetV1MediaResponse = {
  result: models.MediaListResponse;
};

/** @internal */
export const Type$outboundSchema: z.ZodMiniEnum<typeof Type> = z.enum(Type);

/** @internal */
export const GetV1MediaOrder$outboundSchema: z.ZodMiniEnum<
  typeof GetV1MediaOrder
> = z.enum(GetV1MediaOrder);

/** @internal */
export type GetV1MediaRequest$Outbound = {
  limit: number;
  page: number;
  query?: string | undefined;
  type?: string | undefined;
  order: string;
};

/** @internal */
export const GetV1MediaRequest$outboundSchema: z.ZodMiniType<
  GetV1MediaRequest$Outbound,
  GetV1MediaRequest
> = z.object({
  limit: z._default(z.int(), 10),
  page: z._default(z.int(), 1),
  query: z.optional(z.string()),
  type: z.optional(Type$outboundSchema),
  order: z._default(GetV1MediaOrder$outboundSchema, "desc"),
});

export function getV1MediaRequestToJSON(
  getV1MediaRequest: GetV1MediaRequest,
): string {
  return JSON.stringify(
    GetV1MediaRequest$outboundSchema.parse(getV1MediaRequest),
  );
}

/** @internal */
export const GetV1MediaResponse$inboundSchema: z.ZodMiniType<
  GetV1MediaResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.MediaListResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function getV1MediaResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1MediaResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1MediaResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1MediaResponse' from JSON`,
  );
}
