/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type PatchV1MediaIdRequest = {
  /**
   * Media asset ID
   */
  id: string;
  body: models.UpdateMediaBody;
};

/** @internal */
export type PatchV1MediaIdRequest$Outbound = {
  id: string;
  body: models.UpdateMediaBody$Outbound;
};

/** @internal */
export const PatchV1MediaIdRequest$outboundSchema: z.ZodMiniType<
  PatchV1MediaIdRequest$Outbound,
  PatchV1MediaIdRequest
> = z.object({
  id: z.string(),
  body: models.UpdateMediaBody$outboundSchema,
});

export function patchV1MediaIdRequestToJSON(
  patchV1MediaIdRequest: PatchV1MediaIdRequest,
): string {
  return JSON.stringify(
    PatchV1MediaIdRequest$outboundSchema.parse(patchV1MediaIdRequest),
  );
}
