/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type PatchV1TagsIdentifierRequest = {
  /**
   * Tag ID or slug
   */
  identifier: string;
  body: models.UpdateTagBody;
};

/** @internal */
export type PatchV1TagsIdentifierRequest$Outbound = {
  identifier: string;
  body: models.UpdateTagBody$Outbound;
};

/** @internal */
export const PatchV1TagsIdentifierRequest$outboundSchema: z.ZodMiniType<
  PatchV1TagsIdentifierRequest$Outbound,
  PatchV1TagsIdentifierRequest
> = z.object({
  identifier: z.string(),
  body: models.UpdateTagBody$outboundSchema,
});

export function patchV1TagsIdentifierRequestToJSON(
  patchV1TagsIdentifierRequest: PatchV1TagsIdentifierRequest,
): string {
  return JSON.stringify(
    PatchV1TagsIdentifierRequest$outboundSchema.parse(
      patchV1TagsIdentifierRequest,
    ),
  );
}
