/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type PatchV1FieldsIdentifierRequest = {
  /**
   * Field ID or key
   */
  identifier: string;
  body: models.UpdateFieldBody;
};

/** @internal */
export type PatchV1FieldsIdentifierRequest$Outbound = {
  identifier: string;
  body: models.UpdateFieldBody$Outbound;
};

/** @internal */
export const PatchV1FieldsIdentifierRequest$outboundSchema: z.ZodMiniType<
  PatchV1FieldsIdentifierRequest$Outbound,
  PatchV1FieldsIdentifierRequest
> = z.object({
  identifier: z.string(),
  body: models.UpdateFieldBody$outboundSchema,
});

export function patchV1FieldsIdentifierRequestToJSON(
  patchV1FieldsIdentifierRequest: PatchV1FieldsIdentifierRequest,
): string {
  return JSON.stringify(
    PatchV1FieldsIdentifierRequest$outboundSchema.parse(
      patchV1FieldsIdentifierRequest,
    ),
  );
}
