/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type PatchV1CategoriesIdentifierRequest = {
  /**
   * Category ID or slug
   */
  identifier: string;
  body: models.UpdateCategoryBody;
};

/** @internal */
export type PatchV1CategoriesIdentifierRequest$Outbound = {
  identifier: string;
  body: models.UpdateCategoryBody$Outbound;
};

/** @internal */
export const PatchV1CategoriesIdentifierRequest$outboundSchema: z.ZodMiniType<
  PatchV1CategoriesIdentifierRequest$Outbound,
  PatchV1CategoriesIdentifierRequest
> = z.object({
  identifier: z.string(),
  body: models.UpdateCategoryBody$outboundSchema,
});

export function patchV1CategoriesIdentifierRequestToJSON(
  patchV1CategoriesIdentifierRequest: PatchV1CategoriesIdentifierRequest,
): string {
  return JSON.stringify(
    PatchV1CategoriesIdentifierRequest$outboundSchema.parse(
      patchV1CategoriesIdentifierRequest,
    ),
  );
}
