/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type PatchV1PostsIdentifierRequest = {
  /**
   * Post ID or slug
   */
  identifier: string;
  body: models.UpdatePostBody;
};

/** @internal */
export type PatchV1PostsIdentifierRequest$Outbound = {
  identifier: string;
  body: models.UpdatePostBody$Outbound;
};

/** @internal */
export const PatchV1PostsIdentifierRequest$outboundSchema: z.ZodMiniType<
  PatchV1PostsIdentifierRequest$Outbound,
  PatchV1PostsIdentifierRequest
> = z.object({
  identifier: z.string(),
  body: models.UpdatePostBody$outboundSchema,
});

export function patchV1PostsIdentifierRequestToJSON(
  patchV1PostsIdentifierRequest: PatchV1PostsIdentifierRequest,
): string {
  return JSON.stringify(
    PatchV1PostsIdentifierRequest$outboundSchema.parse(
      patchV1PostsIdentifierRequest,
    ),
  );
}
