/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type PatchV1AuthorsIdentifierRequest = {
  /**
   * Author ID or slug
   */
  identifier: string;
  body: models.UpdateAuthorBody;
};

/** @internal */
export type PatchV1AuthorsIdentifierRequest$Outbound = {
  identifier: string;
  body: models.UpdateAuthorBody$Outbound;
};

/** @internal */
export const PatchV1AuthorsIdentifierRequest$outboundSchema: z.ZodMiniType<
  PatchV1AuthorsIdentifierRequest$Outbound,
  PatchV1AuthorsIdentifierRequest
> = z.object({
  identifier: z.string(),
  body: models.UpdateAuthorBody$outboundSchema,
});

export function patchV1AuthorsIdentifierRequestToJSON(
  patchV1AuthorsIdentifierRequest: PatchV1AuthorsIdentifierRequest,
): string {
  return JSON.stringify(
    PatchV1AuthorsIdentifierRequest$outboundSchema.parse(
      patchV1AuthorsIdentifierRequest,
    ),
  );
}
