/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Social, Social$inboundSchema } from "./social.js";

/**
 * Number of published posts by this author
 */
export type AuthorCount = {
  posts: number;
};

export type Author = {
  id: string;
  name: string;
  image: string | null;
  slug: string;
  bio: string | null;
  role: string | null;
  socials: Array<Social>;
  /**
   * Number of published posts by this author
   */
  count?: AuthorCount | undefined;
};

/** @internal */
export const AuthorCount$inboundSchema: z.ZodMiniType<AuthorCount, unknown> = z
  .object({
    posts: types.number(),
  });

export function authorCountFromJSON(
  jsonString: string,
): SafeParseResult<AuthorCount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthorCount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthorCount' from JSON`,
  );
}

/** @internal */
export const Author$inboundSchema: z.ZodMiniType<Author, unknown> = z.object({
  id: types.string(),
  name: types.string(),
  image: types.nullable(types.string()),
  slug: types.string(),
  bio: types.nullable(types.string()),
  role: types.nullable(types.string()),
  socials: z.array(Social$inboundSchema),
  count: types.optional(z.lazy(() => AuthorCount$inboundSchema)),
});

export function authorFromJSON(
  jsonString: string,
): SafeParseResult<Author, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Author$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Author' from JSON`,
  );
}
