/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { Author, Author$inboundSchema } from "./author.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AuthorResponse = {
  author: Author;
};

/** @internal */
export const AuthorResponse$inboundSchema: z.ZodMiniType<
  AuthorResponse,
  unknown
> = z.object({
  author: Author$inboundSchema,
});

export function authorResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthorResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthorResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthorResponse' from JSON`,
  );
}
