/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { Author, Author$inboundSchema } from "./author.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";

export type AuthorsListResponse = {
  authors: Array<Author>;
  pagination: Pagination;
};

/** @internal */
export const AuthorsListResponse$inboundSchema: z.ZodMiniType<
  AuthorsListResponse,
  unknown
> = z.object({
  authors: z.array(Author$inboundSchema),
  pagination: Pagination$inboundSchema,
});

export function authorsListResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthorsListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthorsListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthorsListResponse' from JSON`,
  );
}
