/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { SocialRef, SocialRef$inboundSchema } from "./socialref.js";

export type AuthorRef = {
  id: string;
  name: string;
  image: string | null;
  bio: string | null;
  role: string | null;
  slug: string;
  socials: Array<SocialRef>;
};

/** @internal */
export const AuthorRef$inboundSchema: z.ZodMiniType<AuthorRef, unknown> = z
  .object({
    id: types.string(),
    name: types.string(),
    image: types.nullable(types.string()),
    bio: types.nullable(types.string()),
    role: types.nullable(types.string()),
    slug: types.string(),
    socials: z.array(SocialRef$inboundSchema),
  });

export function authorRefFromJSON(
  jsonString: string,
): SafeParseResult<AuthorRef, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthorRef$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthorRef' from JSON`,
  );
}
