/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Number of published posts in this category
 */
export type CategoryCount = {
  posts: number;
};

export type Category = {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  /**
   * Number of published posts in this category
   */
  count: CategoryCount;
};

/** @internal */
export const CategoryCount$inboundSchema: z.ZodMiniType<
  CategoryCount,
  unknown
> = z.object({
  posts: types.number(),
});

export function categoryCountFromJSON(
  jsonString: string,
): SafeParseResult<CategoryCount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CategoryCount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CategoryCount' from JSON`,
  );
}

/** @internal */
export const Category$inboundSchema: z.ZodMiniType<Category, unknown> = z
  .object({
    id: types.string(),
    name: types.string(),
    slug: types.string(),
    description: types.nullable(types.string()),
    count: z.lazy(() => CategoryCount$inboundSchema),
  });

export function categoryFromJSON(
  jsonString: string,
): SafeParseResult<Category, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Category$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Category' from JSON`,
  );
}
