/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CategoryRef = {
  id: string;
  name: string;
  slug: string;
  description: string | null;
};

/** @internal */
export const CategoryRef$inboundSchema: z.ZodMiniType<CategoryRef, unknown> = z
  .object({
    id: types.string(),
    name: types.string(),
    slug: types.string(),
    description: types.nullable(types.string()),
  });

export function categoryRefFromJSON(
  jsonString: string,
): SafeParseResult<CategoryRef, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CategoryRef$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CategoryRef' from JSON`,
  );
}
