/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { Category, Category$inboundSchema } from "./category.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";

export type CategoriesListResponse = {
  categories: Array<Category>;
  pagination: Pagination;
};

/** @internal */
export const CategoriesListResponse$inboundSchema: z.ZodMiniType<
  CategoriesListResponse,
  unknown
> = z.object({
  categories: z.array(Category$inboundSchema),
  pagination: Pagination$inboundSchema,
});

export function categoriesListResponseFromJSON(
  jsonString: string,
): SafeParseResult<CategoriesListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CategoriesListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CategoriesListResponse' from JSON`,
  );
}
