/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { Category, Category$inboundSchema } from "./category.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CategoryResponse = {
  category: Category;
};

/** @internal */
export const CategoryResponse$inboundSchema: z.ZodMiniType<
  CategoryResponse,
  unknown
> = z.object({
  category: Category$inboundSchema,
});

export function categoryResponseFromJSON(
  jsonString: string,
): SafeParseResult<CategoryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CategoryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CategoryResponse' from JSON`,
  );
}
