/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * Content format (html or markdown)
 */
export const ContentFormat = {
  Html: "html",
  Markdown: "markdown",
} as const;
/**
 * Content format (html or markdown)
 */
export type ContentFormat = ClosedEnum<typeof ContentFormat>;

/** @internal */
export const ContentFormat$outboundSchema: z.ZodMiniEnum<typeof ContentFormat> =
  z.enum(ContentFormat);
