/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CreateCategoryResponseCategory = {
  id: string;
  name: string;
  slug: string;
  description: string | null;
};

export type CreateCategoryResponse = {
  category: CreateCategoryResponseCategory;
};

/** @internal */
export const CreateCategoryResponseCategory$inboundSchema: z.ZodMiniType<
  CreateCategoryResponseCategory,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
  slug: types.string(),
  description: types.nullable(types.string()),
});

export function createCategoryResponseCategoryFromJSON(
  jsonString: string,
): SafeParseResult<CreateCategoryResponseCategory, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateCategoryResponseCategory$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateCategoryResponseCategory' from JSON`,
  );
}

/** @internal */
export const CreateCategoryResponse$inboundSchema: z.ZodMiniType<
  CreateCategoryResponse,
  unknown
> = z.object({
  category: z.lazy(() => CreateCategoryResponseCategory$inboundSchema),
});

export function createCategoryResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateCategoryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateCategoryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateCategoryResponse' from JSON`,
  );
}
