/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CreateTagResponseTag = {
  id: string;
  name: string;
  slug: string;
  description: string | null;
};

export type CreateTagResponse = {
  tag: CreateTagResponseTag;
};

/** @internal */
export const CreateTagResponseTag$inboundSchema: z.ZodMiniType<
  CreateTagResponseTag,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
  slug: types.string(),
  description: types.nullable(types.string()),
});

export function createTagResponseTagFromJSON(
  jsonString: string,
): SafeParseResult<CreateTagResponseTag, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateTagResponseTag$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateTagResponseTag' from JSON`,
  );
}

/** @internal */
export const CreateTagResponse$inboundSchema: z.ZodMiniType<
  CreateTagResponse,
  unknown
> = z.object({
  tag: z.lazy(() => CreateTagResponseTag$inboundSchema),
});

export function createTagResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateTagResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateTagResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateTagResponse' from JSON`,
  );
}
