/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateTagBody = {
  name: string;
  slug: string;
  description?: string | undefined;
};

/** @internal */
export type CreateTagBody$Outbound = {
  name: string;
  slug: string;
  description?: string | undefined;
};

/** @internal */
export const CreateTagBody$outboundSchema: z.ZodMiniType<
  CreateTagBody$Outbound,
  CreateTagBody
> = z.object({
  name: z.string(),
  slug: z.string(),
  description: z.optional(z.string()),
});

export function createTagBodyToJSON(createTagBody: CreateTagBody): string {
  return JSON.stringify(CreateTagBody$outboundSchema.parse(createTagBody));
}
