/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Social, Social$inboundSchema } from "./social.js";

export type CreateAuthorResponseAuthor = {
  id: string;
  name: string;
  slug: string;
  bio: string | null;
  role: string | null;
  image: string | null;
  socials: Array<Social>;
};

export type CreateAuthorResponse = {
  author: CreateAuthorResponseAuthor;
};

/** @internal */
export const CreateAuthorResponseAuthor$inboundSchema: z.ZodMiniType<
  CreateAuthorResponseAuthor,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
  slug: types.string(),
  bio: types.nullable(types.string()),
  role: types.nullable(types.string()),
  image: types.nullable(types.string()),
  socials: z.array(Social$inboundSchema),
});

export function createAuthorResponseAuthorFromJSON(
  jsonString: string,
): SafeParseResult<CreateAuthorResponseAuthor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAuthorResponseAuthor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAuthorResponseAuthor' from JSON`,
  );
}

/** @internal */
export const CreateAuthorResponse$inboundSchema: z.ZodMiniType<
  CreateAuthorResponse,
  unknown
> = z.object({
  author: z.lazy(() => CreateAuthorResponseAuthor$inboundSchema),
});

export function createAuthorResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateAuthorResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAuthorResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAuthorResponse' from JSON`,
  );
}
