/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CreatePostResponsePost = {
  id: string;
  slug: string;
  title: string;
  status: string;
  featured: boolean;
  publishedAt: string;
  createdAt: string;
};

export type CreatePostResponse = {
  post: CreatePostResponsePost;
};

/** @internal */
export const CreatePostResponsePost$inboundSchema: z.ZodMiniType<
  CreatePostResponsePost,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  title: types.string(),
  status: types.string(),
  featured: types.boolean(),
  publishedAt: types.string(),
  createdAt: types.string(),
});

export function createPostResponsePostFromJSON(
  jsonString: string,
): SafeParseResult<CreatePostResponsePost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePostResponsePost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePostResponsePost' from JSON`,
  );
}

/** @internal */
export const CreatePostResponse$inboundSchema: z.ZodMiniType<
  CreatePostResponse,
  unknown
> = z.object({
  post: z.lazy(() => CreatePostResponsePost$inboundSchema),
});

export function createPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreatePostResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePostResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePostResponse' from JSON`,
  );
}
