/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  SocialInput,
  SocialInput$Outbound,
  SocialInput$outboundSchema,
} from "./socialinput.js";

export type CreateAuthorBody = {
  name: string;
  slug: string;
  bio?: string | null | undefined;
  role?: string | null | undefined;
  email?: string | null | undefined;
  image?: string | null | undefined;
  /**
   * Social media links for this author
   */
  socials?: Array<SocialInput> | undefined;
};

/** @internal */
export type CreateAuthorBody$Outbound = {
  name: string;
  slug: string;
  bio?: string | null | undefined;
  role?: string | null | undefined;
  email?: string | null | undefined;
  image?: string | null | undefined;
  socials?: Array<SocialInput$Outbound> | undefined;
};

/** @internal */
export const CreateAuthorBody$outboundSchema: z.ZodMiniType<
  CreateAuthorBody$Outbound,
  CreateAuthorBody
> = z.object({
  name: z.string(),
  slug: z.string(),
  bio: z.optional(z.nullable(z.string())),
  role: z.optional(z.nullable(z.string())),
  email: z.optional(z.nullable(z.string())),
  image: z.optional(z.nullable(z.string())),
  socials: z.optional(z.array(SocialInput$outboundSchema)),
});

export function createAuthorBodyToJSON(
  createAuthorBody: CreateAuthorBody,
): string {
  return JSON.stringify(
    CreateAuthorBody$outboundSchema.parse(createAuthorBody),
  );
}
