/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  FieldOptionInput,
  FieldOptionInput$Outbound,
  FieldOptionInput$outboundSchema,
} from "./fieldoptioninput.js";
import { FieldType, FieldType$outboundSchema } from "./fieldtype.js";

export type CreateFieldBody = {
  key: string;
  name: string;
  description?: string | undefined;
  type: FieldType;
  required?: boolean | undefined;
  /**
   * Required for select and multiselect fields. Not allowed for other field types.
   */
  options?: Array<FieldOptionInput> | undefined;
};

/** @internal */
export type CreateFieldBody$Outbound = {
  key: string;
  name: string;
  description?: string | undefined;
  type: string;
  required?: boolean | undefined;
  options?: Array<FieldOptionInput$Outbound> | undefined;
};

/** @internal */
export const CreateFieldBody$outboundSchema: z.ZodMiniType<
  CreateFieldBody$Outbound,
  CreateFieldBody
> = z.object({
  key: z.string(),
  name: z.string(),
  description: z.optional(z.string()),
  type: FieldType$outboundSchema,
  required: z.optional(z.boolean()),
  options: z.optional(z.array(FieldOptionInput$outboundSchema)),
});

export function createFieldBodyToJSON(
  createFieldBody: CreateFieldBody,
): string {
  return JSON.stringify(CreateFieldBody$outboundSchema.parse(createFieldBody));
}
