/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const CreatePostBodyStatus = {
  Published: "published",
  Draft: "draft",
} as const;
export type CreatePostBodyStatus = ClosedEnum<typeof CreatePostBodyStatus>;

export type CreatePostBody = {
  title: string;
  content: string;
  description: string;
  slug: string;
  categoryId: string;
  status: CreatePostBodyStatus;
  /**
   * Array of tag IDs to attach to the post
   */
  tags?: Array<string> | undefined;
  /**
   * Array of author IDs. If omitted, the first workspace author is used.
   */
  authors?: Array<string> | undefined;
  featured?: boolean | undefined;
  coverImage?: string | null | undefined;
  /**
   * ISO 8601 datetime. Defaults to current time if omitted.
   */
  publishedAt?: Date | undefined;
};

/** @internal */
export const CreatePostBodyStatus$outboundSchema: z.ZodMiniEnum<
  typeof CreatePostBodyStatus
> = z.enum(CreatePostBodyStatus);

/** @internal */
export type CreatePostBody$Outbound = {
  title: string;
  content: string;
  description: string;
  slug: string;
  categoryId: string;
  status: string;
  tags?: Array<string> | undefined;
  authors?: Array<string> | undefined;
  featured: boolean;
  coverImage?: string | null | undefined;
  publishedAt?: string | undefined;
};

/** @internal */
export const CreatePostBody$outboundSchema: z.ZodMiniType<
  CreatePostBody$Outbound,
  CreatePostBody
> = z.object({
  title: z.string(),
  content: z.string(),
  description: z.string(),
  slug: z.string(),
  categoryId: z.string(),
  status: CreatePostBodyStatus$outboundSchema,
  tags: z.optional(z.array(z.string())),
  authors: z.optional(z.array(z.string())),
  featured: z._default(z.boolean(), false),
  coverImage: z.optional(z.nullable(z.string())),
  publishedAt: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
});

export function createPostBodyToJSON(createPostBody: CreatePostBody): string {
  return JSON.stringify(CreatePostBody$outboundSchema.parse(createPostBody));
}
