/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateCategoryBody = {
  name: string;
  slug: string;
  description?: string | undefined;
};

/** @internal */
export type CreateCategoryBody$Outbound = {
  name: string;
  slug: string;
  description?: string | undefined;
};

/** @internal */
export const CreateCategoryBody$outboundSchema: z.ZodMiniType<
  CreateCategoryBody$Outbound,
  CreateCategoryBody
> = z.object({
  name: z.string(),
  slug: z.string(),
  description: z.optional(z.string()),
});

export function createCategoryBodyToJSON(
  createCategoryBody: CreateCategoryBody,
): string {
  return JSON.stringify(
    CreateCategoryBody$outboundSchema.parse(createCategoryBody),
  );
}
