/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type DeleteResponse = {
  id: string;
};

/** @internal */
export const DeleteResponse$inboundSchema: z.ZodMiniType<
  DeleteResponse,
  unknown
> = z.object({
  id: types.string(),
});

export function deleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteResponse' from JSON`,
  );
}
