/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { FieldOption, FieldOption$inboundSchema } from "./fieldoption.js";
import { FieldType, FieldType$inboundSchema } from "./fieldtype.js";

export type Field = {
  id: string;
  key: string;
  name: string;
  description: string | null;
  type: FieldType;
  required: boolean;
  position: number;
  options: Array<FieldOption>;
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const Field$inboundSchema: z.ZodMiniType<Field, unknown> = z.object({
  id: types.string(),
  key: types.string(),
  name: types.string(),
  description: types.nullable(types.string()),
  type: FieldType$inboundSchema,
  required: types.boolean(),
  position: types.number(),
  options: z.array(FieldOption$inboundSchema),
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function fieldFromJSON(
  jsonString: string,
): SafeParseResult<Field, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Field$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Field' from JSON`,
  );
}
