/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type FieldOptionInput = {
  value: string;
  label: string;
};

/** @internal */
export type FieldOptionInput$Outbound = {
  value: string;
  label: string;
};

/** @internal */
export const FieldOptionInput$outboundSchema: z.ZodMiniType<
  FieldOptionInput$Outbound,
  FieldOptionInput
> = z.object({
  value: z.string(),
  label: z.string(),
});

export function fieldOptionInputToJSON(
  fieldOptionInput: FieldOptionInput,
): string {
  return JSON.stringify(
    FieldOptionInput$outboundSchema.parse(fieldOptionInput),
  );
}
