/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Field, Field$inboundSchema } from "./field.js";

export type FieldsListResponse = {
  fields: Array<Field>;
};

/** @internal */
export const FieldsListResponse$inboundSchema: z.ZodMiniType<
  FieldsListResponse,
  unknown
> = z.object({
  fields: z.array(Field$inboundSchema),
});

export function fieldsListResponseFromJSON(
  jsonString: string,
): SafeParseResult<FieldsListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FieldsListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FieldsListResponse' from JSON`,
  );
}
