/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type FieldOption = {
  id: string;
  value: string;
  label: string;
  position: number;
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const FieldOption$inboundSchema: z.ZodMiniType<FieldOption, unknown> = z
  .object({
    id: types.string(),
    value: types.string(),
    label: types.string(),
    position: types.number(),
    createdAt: types.date(),
    updatedAt: types.date(),
  });

export function fieldOptionFromJSON(
  jsonString: string,
): SafeParseResult<FieldOption, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FieldOption$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FieldOption' from JSON`,
  );
}
