/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const FieldType = {
  Text: "text",
  Number: "number",
  Boolean: "boolean",
  Date: "date",
  Richtext: "richtext",
  Select: "select",
  Multiselect: "multiselect",
} as const;
export type FieldType = OpenEnum<typeof FieldType>;

/** @internal */
export const FieldType$inboundSchema: z.ZodMiniType<FieldType, unknown> =
  openEnums.inboundSchema(FieldType);
/** @internal */
export const FieldType$outboundSchema: z.ZodMiniType<string, FieldType> =
  openEnums.outboundSchema(FieldType);
