/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Media, Media$inboundSchema } from "./media.js";

export type MediaResponse = {
  media: Media;
};

/** @internal */
export const MediaResponse$inboundSchema: z.ZodMiniType<
  MediaResponse,
  unknown
> = z.object({
  media: Media$inboundSchema,
});

export function mediaResponseFromJSON(
  jsonString: string,
): SafeParseResult<MediaResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MediaResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MediaResponse' from JSON`,
  );
}
