/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { MediaType, MediaType$inboundSchema } from "./mediatype.js";

export type Media = {
  id: string;
  name: string;
  url: string;
  alt: string | null;
  /**
   * File size in bytes
   */
  size: number;
  mimeType: string | null;
  width: number | null;
  height: number | null;
  /**
   * Duration in milliseconds
   */
  duration: number | null;
  blurHash: string | null;
  type: MediaType;
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const Media$inboundSchema: z.ZodMiniType<Media, unknown> = z.object({
  id: types.string(),
  name: types.string(),
  url: types.string(),
  alt: types.nullable(types.string()),
  size: types.number(),
  mimeType: types.nullable(types.string()),
  width: types.nullable(types.number()),
  height: types.nullable(types.number()),
  duration: types.nullable(types.number()),
  blurHash: types.nullable(types.string()),
  type: MediaType$inboundSchema,
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function mediaFromJSON(
  jsonString: string,
): SafeParseResult<Media, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Media$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Media' from JSON`,
  );
}
