/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Media, Media$inboundSchema } from "./media.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";

export type MediaListResponse = {
  media: Array<Media>;
  pagination: Pagination;
};

/** @internal */
export const MediaListResponse$inboundSchema: z.ZodMiniType<
  MediaListResponse,
  unknown
> = z.object({
  media: z.array(Media$inboundSchema),
  pagination: Pagination$inboundSchema,
});

export function mediaListResponseFromJSON(
  jsonString: string,
): SafeParseResult<MediaListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MediaListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MediaListResponse' from JSON`,
  );
}
