/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ErrorT = {
  InvalidPageNumber: "Invalid page number",
} as const;
export type ErrorT = ClosedEnum<typeof ErrorT>;

export type Details = {
  message: string;
  totalPages: number;
  requestedPage: number;
};

/** @internal */
export const ErrorT$inboundSchema: z.ZodMiniEnum<typeof ErrorT> = z.enum(
  ErrorT,
);

/** @internal */
export const Details$inboundSchema: z.ZodMiniType<Details, unknown> = z.object({
  message: types.string(),
  totalPages: types.number(),
  requestedPage: types.number(),
});

export function detailsFromJSON(
  jsonString: string,
): SafeParseResult<Details, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Details$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Details' from JSON`,
  );
}
