/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Post, Post$inboundSchema } from "./post.js";

export type PostResponse = {
  post: Post;
};

/** @internal */
export const PostResponse$inboundSchema: z.ZodMiniType<PostResponse, unknown> =
  z.object({
    post: Post$inboundSchema,
  });

export function postResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostResponse' from JSON`,
  );
}
