/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { AuthorRef, AuthorRef$inboundSchema } from "./authorref.js";
import { CategoryRef, CategoryRef$inboundSchema } from "./categoryref.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { TagRef, TagRef$inboundSchema } from "./tagref.js";

/**
 * Attribution to the original author when republishing content
 */
export type Attribution = {
  author: string;
  url: string;
};

export type Post = {
  id: string;
  slug: string;
  title: string;
  content: string;
  featured: boolean;
  coverImage: string | null;
  description: string;
  publishedAt: Date;
  updatedAt: Date;
  /**
   * Attribution to the original author when republishing content
   */
  attribution: Attribution | null;
  authors: Array<AuthorRef>;
  category: CategoryRef | null;
  tags: Array<TagRef>;
};

/** @internal */
export const Attribution$inboundSchema: z.ZodMiniType<Attribution, unknown> = z
  .object({
    author: types.string(),
    url: types.string(),
  });

export function attributionFromJSON(
  jsonString: string,
): SafeParseResult<Attribution, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Attribution$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Attribution' from JSON`,
  );
}

/** @internal */
export const Post$inboundSchema: z.ZodMiniType<Post, unknown> = z.object({
  id: types.string(),
  slug: types.string(),
  title: types.string(),
  content: types.string(),
  featured: types.boolean(),
  coverImage: types.nullable(types.string()),
  description: types.string(),
  publishedAt: types.date(),
  updatedAt: types.date(),
  attribution: types.nullable(z.lazy(() => Attribution$inboundSchema)),
  authors: z.array(AuthorRef$inboundSchema),
  category: types.nullable(CategoryRef$inboundSchema),
  tags: z.array(TagRef$inboundSchema),
});

export function postFromJSON(
  jsonString: string,
): SafeParseResult<Post, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Post$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Post' from JSON`,
  );
}
