/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { AuthorRef, AuthorRef$inboundSchema } from "./authorref.js";
import { CategoryRef, CategoryRef$inboundSchema } from "./categoryref.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { TagRef, TagRef$inboundSchema } from "./tagref.js";

export const PostStatus = {
  Published: "published",
  Draft: "draft",
} as const;
export type PostStatus = OpenEnum<typeof PostStatus>;

export type Fields = string | number | boolean | Array<string> | any;

export type Post = {
  id: string;
  slug: string;
  title: string;
  status: PostStatus;
  featured: boolean;
  coverImage: string | null;
  description: string;
  publishedAt: Date;
  updatedAt: Date;
  authors: Array<AuthorRef>;
  category: CategoryRef;
  tags: Array<TagRef>;
  /**
   * Custom field values keyed by field key
   */
  fields: {
    [k: string]: string | number | boolean | Array<string> | any | null;
  };
  content: string;
};

/** @internal */
export const PostStatus$inboundSchema: z.ZodMiniType<PostStatus, unknown> =
  openEnums.inboundSchema(PostStatus);

/** @internal */
export const Fields$inboundSchema: z.ZodMiniType<Fields, unknown> = smartUnion([
  types.string(),
  types.number(),
  types.boolean(),
  z.array(types.string()),
  z.any(),
]);

export function fieldsFromJSON(
  jsonString: string,
): SafeParseResult<Fields, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Fields$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Fields' from JSON`,
  );
}

/** @internal */
export const Post$inboundSchema: z.ZodMiniType<Post, unknown> = z.object({
  id: types.string(),
  slug: types.string(),
  title: types.string(),
  status: PostStatus$inboundSchema,
  featured: types.boolean(),
  coverImage: types.nullable(types.string()),
  description: types.string(),
  publishedAt: types.date(),
  updatedAt: types.date(),
  authors: z.array(AuthorRef$inboundSchema),
  category: CategoryRef$inboundSchema,
  tags: z.array(TagRef$inboundSchema),
  fields: z.record(
    z.string(),
    types.nullable(
      smartUnion([
        types.string(),
        types.number(),
        types.boolean(),
        z.array(types.string()),
        z.any(),
      ]),
    ),
  ),
  content: types.string(),
});

export function postFromJSON(
  jsonString: string,
): SafeParseResult<Post, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Post$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Post' from JSON`,
  );
}
