/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";
import { PostListItem, PostListItem$inboundSchema } from "./postlistitem.js";

export type PostsListResponse = {
  posts: Array<PostListItem>;
  pagination: Pagination;
};

/** @internal */
export const PostsListResponse$inboundSchema: z.ZodMiniType<
  PostsListResponse,
  unknown
> = z.object({
  posts: z.array(PostListItem$inboundSchema),
  pagination: Pagination$inboundSchema,
});

export function postsListResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostsListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostsListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostsListResponse' from JSON`,
  );
}
