/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { AuthorRef, AuthorRef$inboundSchema } from "./authorref.js";
import { CategoryRef, CategoryRef$inboundSchema } from "./categoryref.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { TagRef, TagRef$inboundSchema } from "./tagref.js";

/**
 * Attribution to the original author when republishing content
 */
export type PostListItemAttribution = {
  author: string;
  url: string;
};

export type PostListItem = {
  id: string;
  slug: string;
  title: string;
  featured: boolean;
  coverImage: string | null;
  description: string;
  publishedAt: Date;
  updatedAt: Date;
  /**
   * Attribution to the original author when republishing content
   */
  attribution: PostListItemAttribution | null;
  authors: Array<AuthorRef>;
  category: CategoryRef;
  tags: Array<TagRef>;
  /**
   * Full post content. Only included when content=true (default).
   */
  content?: string | undefined;
};

/** @internal */
export const PostListItemAttribution$inboundSchema: z.ZodMiniType<
  PostListItemAttribution,
  unknown
> = z.object({
  author: types.string(),
  url: types.string(),
});

export function postListItemAttributionFromJSON(
  jsonString: string,
): SafeParseResult<PostListItemAttribution, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostListItemAttribution$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostListItemAttribution' from JSON`,
  );
}

/** @internal */
export const PostListItem$inboundSchema: z.ZodMiniType<PostListItem, unknown> =
  z.object({
    id: types.string(),
    slug: types.string(),
    title: types.string(),
    featured: types.boolean(),
    coverImage: types.nullable(types.string()),
    description: types.string(),
    publishedAt: types.date(),
    updatedAt: types.date(),
    attribution: types.nullable(
      z.lazy(() => PostListItemAttribution$inboundSchema),
    ),
    authors: z.array(AuthorRef$inboundSchema),
    category: CategoryRef$inboundSchema,
    tags: z.array(TagRef$inboundSchema),
    content: types.optional(types.string()),
  });

export function postListItemFromJSON(
  jsonString: string,
): SafeParseResult<PostListItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostListItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostListItem' from JSON`,
  );
}
