/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { AuthorRef, AuthorRef$inboundSchema } from "./authorref.js";
import { CategoryRef, CategoryRef$inboundSchema } from "./categoryref.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { TagRef, TagRef$inboundSchema } from "./tagref.js";

export const PostListItemStatus = {
  Published: "published",
  Draft: "draft",
} as const;
export type PostListItemStatus = OpenEnum<typeof PostListItemStatus>;

/**
 * Attribution to the original author when republishing content
 */
export type PostListItemAttribution = {
  author: string;
  url: string;
};

export type PostListItemFields =
  | string
  | number
  | boolean
  | Array<string>
  | any;

export type PostListItem = {
  id: string;
  slug: string;
  title: string;
  status: PostListItemStatus;
  featured: boolean;
  coverImage: string | null;
  description: string;
  publishedAt: Date;
  updatedAt: Date;
  /**
   * Attribution to the original author when republishing content
   */
  attribution: PostListItemAttribution | null;
  authors: Array<AuthorRef>;
  category: CategoryRef;
  tags: Array<TagRef>;
  /**
   * Custom field values keyed by field key
   */
  fields: {
    [k: string]: string | number | boolean | Array<string> | any | null;
  };
  content: string;
};

/** @internal */
export const PostListItemStatus$inboundSchema: z.ZodMiniType<
  PostListItemStatus,
  unknown
> = openEnums.inboundSchema(PostListItemStatus);

/** @internal */
export const PostListItemAttribution$inboundSchema: z.ZodMiniType<
  PostListItemAttribution,
  unknown
> = z.object({
  author: types.string(),
  url: types.string(),
});

export function postListItemAttributionFromJSON(
  jsonString: string,
): SafeParseResult<PostListItemAttribution, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostListItemAttribution$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostListItemAttribution' from JSON`,
  );
}

/** @internal */
export const PostListItemFields$inboundSchema: z.ZodMiniType<
  PostListItemFields,
  unknown
> = smartUnion([
  types.string(),
  types.number(),
  types.boolean(),
  z.array(types.string()),
  z.any(),
]);

export function postListItemFieldsFromJSON(
  jsonString: string,
): SafeParseResult<PostListItemFields, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostListItemFields$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostListItemFields' from JSON`,
  );
}

/** @internal */
export const PostListItem$inboundSchema: z.ZodMiniType<PostListItem, unknown> =
  z.object({
    id: types.string(),
    slug: types.string(),
    title: types.string(),
    status: PostListItemStatus$inboundSchema,
    featured: types.boolean(),
    coverImage: types.nullable(types.string()),
    description: types.string(),
    publishedAt: types.date(),
    updatedAt: types.date(),
    attribution: types.nullable(
      z.lazy(() => PostListItemAttribution$inboundSchema),
    ),
    authors: z.array(AuthorRef$inboundSchema),
    category: CategoryRef$inboundSchema,
    tags: z.array(TagRef$inboundSchema),
    fields: z.record(
      z.string(),
      types.nullable(
        smartUnion([
          types.string(),
          types.number(),
          types.boolean(),
          z.array(types.string()),
          z.any(),
        ]),
      ),
    ),
    content: types.string(),
  });

export function postListItemFromJSON(
  jsonString: string,
): SafeParseResult<PostListItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostListItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostListItem' from JSON`,
  );
}
