/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Post, Post$inboundSchema } from "./post.js";

export type SinglePostResponse = {
  post: Post;
};

/** @internal */
export const SinglePostResponse$inboundSchema: z.ZodMiniType<
  SinglePostResponse,
  unknown
> = z.object({
  post: Post$inboundSchema,
});

export function singlePostResponseFromJSON(
  jsonString: string,
): SafeParseResult<SinglePostResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SinglePostResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SinglePostResponse' from JSON`,
  );
}
