/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Tag, Tag$inboundSchema } from "./tag.js";

export type SingleTagResponse = {
  tag: Tag;
};

/** @internal */
export const SingleTagResponse$inboundSchema: z.ZodMiniType<
  SingleTagResponse,
  unknown
> = z.object({
  tag: Tag$inboundSchema,
});

export function singleTagResponseFromJSON(
  jsonString: string,
): SafeParseResult<SingleTagResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SingleTagResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SingleTagResponse' from JSON`,
  );
}
