/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Social = {
  url: string;
  platform: string;
};

/** @internal */
export const Social$inboundSchema: z.ZodMiniType<Social, unknown> = z.object({
  url: types.string(),
  platform: types.string(),
});

export function socialFromJSON(
  jsonString: string,
): SafeParseResult<Social, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Social$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Social' from JSON`,
  );
}
