/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type SocialRef = {
  url: string;
  platform: string;
};

/** @internal */
export const SocialRef$inboundSchema: z.ZodMiniType<SocialRef, unknown> = z
  .object({
    url: types.string(),
    platform: types.string(),
  });

export function socialRefFromJSON(
  jsonString: string,
): SafeParseResult<SocialRef, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SocialRef$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SocialRef' from JSON`,
  );
}
