/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const Platform = {
  X: "x",
  Twitter: "twitter",
  Github: "github",
  Facebook: "facebook",
  Instagram: "instagram",
  Youtube: "youtube",
  Tiktok: "tiktok",
  Linkedin: "linkedin",
  Website: "website",
  Onlyfans: "onlyfans",
  Discord: "discord",
  Bluesky: "bluesky",
} as const;
export type Platform = ClosedEnum<typeof Platform>;

export type SocialInput = {
  platform: Platform;
  url: string;
};

/** @internal */
export const Platform$outboundSchema: z.ZodMiniEnum<typeof Platform> = z.enum(
  Platform,
);

/** @internal */
export type SocialInput$Outbound = {
  platform: string;
  url: string;
};

/** @internal */
export const SocialInput$outboundSchema: z.ZodMiniType<
  SocialInput$Outbound,
  SocialInput
> = z.object({
  platform: Platform$outboundSchema,
  url: z.string(),
});

export function socialInputToJSON(socialInput: SocialInput): string {
  return JSON.stringify(SocialInput$outboundSchema.parse(socialInput));
}
