/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Number of published posts with this tag
 */
export type TagCount = {
  posts: number;
};

export type Tag = {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  /**
   * Number of published posts with this tag
   */
  count: TagCount;
};

/** @internal */
export const TagCount$inboundSchema: z.ZodMiniType<TagCount, unknown> = z
  .object({
    posts: types.number(),
  });

export function tagCountFromJSON(
  jsonString: string,
): SafeParseResult<TagCount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TagCount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TagCount' from JSON`,
  );
}

/** @internal */
export const Tag$inboundSchema: z.ZodMiniType<Tag, unknown> = z.object({
  id: types.string(),
  name: types.string(),
  slug: types.string(),
  description: types.nullable(types.string()),
  count: z.lazy(() => TagCount$inboundSchema),
});

export function tagFromJSON(
  jsonString: string,
): SafeParseResult<Tag, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Tag$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Tag' from JSON`,
  );
}
