/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Tag, Tag$inboundSchema } from "./tag.js";

export type TagResponse = {
  tag: Tag;
};

/** @internal */
export const TagResponse$inboundSchema: z.ZodMiniType<TagResponse, unknown> = z
  .object({
    tag: Tag$inboundSchema,
  });

export function tagResponseFromJSON(
  jsonString: string,
): SafeParseResult<TagResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TagResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TagResponse' from JSON`,
  );
}
