/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type TagRef = {
  id: string;
  name: string;
  slug: string;
  description: string | null;
};

/** @internal */
export const TagRef$inboundSchema: z.ZodMiniType<TagRef, unknown> = z.object({
  id: types.string(),
  name: types.string(),
  slug: types.string(),
  description: types.nullable(types.string()),
});

export function tagRefFromJSON(
  jsonString: string,
): SafeParseResult<TagRef, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TagRef$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TagRef' from JSON`,
  );
}
