/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";
import { Tag, Tag$inboundSchema } from "./tag.js";

export type TagsListResponse = {
  tags: Array<Tag>;
  pagination: Pagination;
};

/** @internal */
export const TagsListResponse$inboundSchema: z.ZodMiniType<
  TagsListResponse,
  unknown
> = z.object({
  tags: z.array(Tag$inboundSchema),
  pagination: Pagination$inboundSchema,
});

export function tagsListResponseFromJSON(
  jsonString: string,
): SafeParseResult<TagsListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TagsListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TagsListResponse' from JSON`,
  );
}
