/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type UpdateTagBody = {
  name?: string | undefined;
  slug?: string | undefined;
  description?: string | null | undefined;
};

/** @internal */
export type UpdateTagBody$Outbound = {
  name?: string | undefined;
  slug?: string | undefined;
  description?: string | null | undefined;
};

/** @internal */
export const UpdateTagBody$outboundSchema: z.ZodMiniType<
  UpdateTagBody$Outbound,
  UpdateTagBody
> = z.object({
  name: z.optional(z.string()),
  slug: z.optional(z.string()),
  description: z.optional(z.nullable(z.string())),
});

export function updateTagBodyToJSON(updateTagBody: UpdateTagBody): string {
  return JSON.stringify(UpdateTagBody$outboundSchema.parse(updateTagBody));
}
