/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const UpdatePostBodyStatus = {
  Published: "published",
  Draft: "draft",
} as const;
export type UpdatePostBodyStatus = ClosedEnum<typeof UpdatePostBodyStatus>;

export type UpdatePostBody = {
  title?: string | undefined;
  content?: string | undefined;
  description?: string | undefined;
  slug?: string | undefined;
  categoryId?: string | undefined;
  status?: UpdatePostBodyStatus | undefined;
  /**
   * Array of tag IDs. Replaces all existing tags when provided.
   */
  tags?: Array<string> | undefined;
  /**
   * Array of author IDs. Replaces all existing authors when provided.
   */
  authors?: Array<string> | undefined;
  featured?: boolean | undefined;
  coverImage?: string | null | undefined;
  publishedAt?: Date | undefined;
};

/** @internal */
export const UpdatePostBodyStatus$outboundSchema: z.ZodMiniEnum<
  typeof UpdatePostBodyStatus
> = z.enum(UpdatePostBodyStatus);

/** @internal */
export type UpdatePostBody$Outbound = {
  title?: string | undefined;
  content?: string | undefined;
  description?: string | undefined;
  slug?: string | undefined;
  categoryId?: string | undefined;
  status?: string | undefined;
  tags?: Array<string> | undefined;
  authors?: Array<string> | undefined;
  featured?: boolean | undefined;
  coverImage?: string | null | undefined;
  publishedAt?: string | undefined;
};

/** @internal */
export const UpdatePostBody$outboundSchema: z.ZodMiniType<
  UpdatePostBody$Outbound,
  UpdatePostBody
> = z.object({
  title: z.optional(z.string()),
  content: z.optional(z.string()),
  description: z.optional(z.string()),
  slug: z.optional(z.string()),
  categoryId: z.optional(z.string()),
  status: z.optional(UpdatePostBodyStatus$outboundSchema),
  tags: z.optional(z.array(z.string())),
  authors: z.optional(z.array(z.string())),
  featured: z.optional(z.boolean()),
  coverImage: z.optional(z.nullable(z.string())),
  publishedAt: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
});

export function updatePostBodyToJSON(updatePostBody: UpdatePostBody): string {
  return JSON.stringify(UpdatePostBody$outboundSchema.parse(updatePostBody));
}
