/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  SocialInput,
  SocialInput$Outbound,
  SocialInput$outboundSchema,
} from "./socialinput.js";

export type UpdateAuthorBody = {
  name?: string | undefined;
  slug?: string | undefined;
  bio?: string | null | undefined;
  role?: string | null | undefined;
  email?: string | null | undefined;
  image?: string | null | undefined;
  /**
   * Social media links. Replaces all existing socials when provided.
   */
  socials?: Array<SocialInput> | undefined;
};

/** @internal */
export type UpdateAuthorBody$Outbound = {
  name?: string | undefined;
  slug?: string | undefined;
  bio?: string | null | undefined;
  role?: string | null | undefined;
  email?: string | null | undefined;
  image?: string | null | undefined;
  socials?: Array<SocialInput$Outbound> | undefined;
};

/** @internal */
export const UpdateAuthorBody$outboundSchema: z.ZodMiniType<
  UpdateAuthorBody$Outbound,
  UpdateAuthorBody
> = z.object({
  name: z.optional(z.string()),
  slug: z.optional(z.string()),
  bio: z.optional(z.nullable(z.string())),
  role: z.optional(z.nullable(z.string())),
  email: z.optional(z.nullable(z.string())),
  image: z.optional(z.nullable(z.string())),
  socials: z.optional(z.array(SocialInput$outboundSchema)),
});

export function updateAuthorBodyToJSON(
  updateAuthorBody: UpdateAuthorBody,
): string {
  return JSON.stringify(
    UpdateAuthorBody$outboundSchema.parse(updateAuthorBody),
  );
}
