/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type UpdateMediaBody = {
  name?: string | undefined;
  alt?: string | null | undefined;
};

/** @internal */
export type UpdateMediaBody$Outbound = {
  name?: string | undefined;
  alt?: string | null | undefined;
};

/** @internal */
export const UpdateMediaBody$outboundSchema: z.ZodMiniType<
  UpdateMediaBody$Outbound,
  UpdateMediaBody
> = z.object({
  name: z.optional(z.string()),
  alt: z.optional(z.nullable(z.string())),
});

export function updateMediaBodyToJSON(
  updateMediaBody: UpdateMediaBody,
): string {
  return JSON.stringify(UpdateMediaBody$outboundSchema.parse(updateMediaBody));
}
