/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  FieldOptionInput,
  FieldOptionInput$Outbound,
  FieldOptionInput$outboundSchema,
} from "./fieldoptioninput.js";
import { FieldType, FieldType$outboundSchema } from "./fieldtype.js";

export type UpdateFieldBody = {
  key?: string | undefined;
  name?: string | undefined;
  description?: string | null | undefined;
  type?: FieldType | undefined;
  required?: boolean | undefined;
  /**
   * Replacement option list. Only valid for select and multiselect fields.
   */
  options?: Array<FieldOptionInput> | undefined;
};

/** @internal */
export type UpdateFieldBody$Outbound = {
  key?: string | undefined;
  name?: string | undefined;
  description?: string | null | undefined;
  type?: string | undefined;
  required?: boolean | undefined;
  options?: Array<FieldOptionInput$Outbound> | undefined;
};

/** @internal */
export const UpdateFieldBody$outboundSchema: z.ZodMiniType<
  UpdateFieldBody$Outbound,
  UpdateFieldBody
> = z.object({
  key: z.optional(z.string()),
  name: z.optional(z.string()),
  description: z.optional(z.nullable(z.string())),
  type: z.optional(FieldType$outboundSchema),
  required: z.optional(z.boolean()),
  options: z.optional(z.array(FieldOptionInput$outboundSchema)),
});

export function updateFieldBodyToJSON(
  updateFieldBody: UpdateFieldBody,
): string {
  return JSON.stringify(UpdateFieldBody$outboundSchema.parse(updateFieldBody));
}
