/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type UpdateCategoryBody = {
  name?: string | undefined;
  slug?: string | undefined;
  description?: string | null | undefined;
};

/** @internal */
export type UpdateCategoryBody$Outbound = {
  name?: string | undefined;
  slug?: string | undefined;
  description?: string | null | undefined;
};

/** @internal */
export const UpdateCategoryBody$outboundSchema: z.ZodMiniType<
  UpdateCategoryBody$Outbound,
  UpdateCategoryBody
> = z.object({
  name: z.optional(z.string()),
  slug: z.optional(z.string()),
  description: z.optional(z.nullable(z.string())),
});

export function updateCategoryBodyToJSON(
  updateCategoryBody: UpdateCategoryBody,
): string {
  return JSON.stringify(
    UpdateCategoryBody$outboundSchema.parse(updateCategoryBody),
  );
}
