/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";
import { smartUnion } from "../types/smartUnion.js";

export const UpdatePostBodyStatus = {
  Published: "published",
  Draft: "draft",
} as const;
export type UpdatePostBodyStatus = ClosedEnum<typeof UpdatePostBodyStatus>;

export type UpdatePostBodyFields =
  | string
  | number
  | boolean
  | Array<string>
  | any;

export type UpdatePostBody = {
  title?: string | undefined;
  content?: string | undefined;
  description?: string | undefined;
  slug?: string | undefined;
  categoryId?: string | undefined;
  status?: UpdatePostBodyStatus | undefined;
  /**
   * Array of tag IDs. Replaces all existing tags when provided.
   */
  tags?: Array<string> | undefined;
  /**
   * Array of author IDs. Replaces all existing authors when provided.
   */
  authors?: Array<string> | undefined;
  featured?: boolean | undefined;
  coverImage?: string | null | undefined;
  publishedAt?: Date | undefined;
  /**
   * Custom field values keyed by field key. Select values must use option values; multiselect values must be arrays of option values. Use null to clear optional fields.
   */
  fields?: {
    [k: string]: string | number | boolean | Array<string> | any | null;
  } | undefined;
};

/** @internal */
export const UpdatePostBodyStatus$outboundSchema: z.ZodMiniEnum<
  typeof UpdatePostBodyStatus
> = z.enum(UpdatePostBodyStatus);

/** @internal */
export type UpdatePostBodyFields$Outbound =
  | string
  | number
  | boolean
  | Array<string>
  | any;

/** @internal */
export const UpdatePostBodyFields$outboundSchema: z.ZodMiniType<
  UpdatePostBodyFields$Outbound,
  UpdatePostBodyFields
> = smartUnion([
  z.string(),
  z.number(),
  z.boolean(),
  z.array(z.string()),
  z.any(),
]);

export function updatePostBodyFieldsToJSON(
  updatePostBodyFields: UpdatePostBodyFields,
): string {
  return JSON.stringify(
    UpdatePostBodyFields$outboundSchema.parse(updatePostBodyFields),
  );
}

/** @internal */
export type UpdatePostBody$Outbound = {
  title?: string | undefined;
  content?: string | undefined;
  description?: string | undefined;
  slug?: string | undefined;
  categoryId?: string | undefined;
  status?: string | undefined;
  tags?: Array<string> | undefined;
  authors?: Array<string> | undefined;
  featured?: boolean | undefined;
  coverImage?: string | null | undefined;
  publishedAt?: string | undefined;
  fields?: {
    [k: string]: string | number | boolean | Array<string> | any | null;
  } | undefined;
};

/** @internal */
export const UpdatePostBody$outboundSchema: z.ZodMiniType<
  UpdatePostBody$Outbound,
  UpdatePostBody
> = z.object({
  title: z.optional(z.string()),
  content: z.optional(z.string()),
  description: z.optional(z.string()),
  slug: z.optional(z.string()),
  categoryId: z.optional(z.string()),
  status: z.optional(UpdatePostBodyStatus$outboundSchema),
  tags: z.optional(z.array(z.string())),
  authors: z.optional(z.array(z.string())),
  featured: z.optional(z.boolean()),
  coverImage: z.optional(z.nullable(z.string())),
  publishedAt: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  fields: z.optional(
    z.record(
      z.string(),
      z.nullable(
        smartUnion([
          z.string(),
          z.number(),
          z.boolean(),
          z.array(z.string()),
          z.any(),
        ]),
      ),
    ),
  ),
});

export function updatePostBodyToJSON(updatePostBody: UpdatePostBody): string {
  return JSON.stringify(UpdatePostBody$outboundSchema.parse(updatePostBody));
}
