/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type UpdatePostResponsePost = {
  id: string;
  slug: string;
  title: string;
  status: string;
  featured: boolean;
  publishedAt: string;
  updatedAt: string;
};

export type UpdatePostResponse = {
  post: UpdatePostResponsePost;
};

/** @internal */
export const UpdatePostResponsePost$inboundSchema: z.ZodMiniType<
  UpdatePostResponsePost,
  unknown
> = z.object({
  id: types.string(),
  slug: types.string(),
  title: types.string(),
  status: types.string(),
  featured: types.boolean(),
  publishedAt: types.string(),
  updatedAt: types.string(),
});

export function updatePostResponsePostFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePostResponsePost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePostResponsePost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePostResponsePost' from JSON`,
  );
}

/** @internal */
export const UpdatePostResponse$inboundSchema: z.ZodMiniType<
  UpdatePostResponse,
  unknown
> = z.object({
  post: z.lazy(() => UpdatePostResponsePost$inboundSchema),
});

export function updatePostResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePostResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePostResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePostResponse' from JSON`,
  );
}
