/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { blobLikeSchema } from "../types/blobs.js";

export type FileT = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type UploadMediaBody = {
  /**
   * Media file to upload. Maximum size: 5 MiB.
   */
  file?: FileT | Blob | undefined;
  name?: string | undefined;
  alt?: string | undefined;
};

/** @internal */
export type FileT$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const FileT$outboundSchema: z.ZodMiniType<FileT$Outbound, FileT> = z
  .object({
    fileName: z.string(),
    content: z.union([
      z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
      z.custom<Blob>(x => x instanceof Blob),
      z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
      z.custom<Uint8Array>(x => x instanceof Uint8Array),
    ]),
  });

export function fileToJSON(fileT: FileT): string {
  return JSON.stringify(FileT$outboundSchema.parse(fileT));
}

/** @internal */
export type UploadMediaBody$Outbound = {
  file?: FileT$Outbound | Blob | undefined;
  name?: string | undefined;
  alt?: string | undefined;
};

/** @internal */
export const UploadMediaBody$outboundSchema: z.ZodMiniType<
  UploadMediaBody$Outbound,
  UploadMediaBody
> = z.object({
  file: z.optional(
    z.union([z.lazy(() => FileT$outboundSchema), blobLikeSchema]),
  ),
  name: z.optional(z.string()),
  alt: z.optional(z.string()),
});

export function uploadMediaBodyToJSON(
  uploadMediaBody: UploadMediaBody,
): string {
  return JSON.stringify(UploadMediaBody$outboundSchema.parse(uploadMediaBody));
}
